"""
report_generator.py - Downloadable Report Generator
=====================================================
Generates professional CSV and PDF reports containing student
profiles, internship recommendations, skill gap analyses,
and readiness scores.
"""

import io
import csv
from datetime import datetime

import pandas as pd

try:
    from fpdf import FPDF
    HAS_FPDF = True
    FPDF_ERROR = None
except Exception as e:
    import traceback
    HAS_FPDF = False
    FPDF_ERROR = traceback.format_exc()


def generate_csv_report(
    student_profile: dict,
    recommendations: list[dict],
    skill_gap: dict,
    readiness_score: float,
) -> bytes:
    """
    Generate a CSV report with multiple sections.

    Returns
    -------
    bytes
        CSV file content as bytes.
    """
    output = io.StringIO()
    writer = csv.writer(output)

    # ── Section 1: Student Profile ────────────────────────────────────────
    writer.writerow(["=== STUDENT PROFILE ==="])
    writer.writerow(["Field", "Value"])
    writer.writerow(["Name", student_profile.get("name", "N/A")])
    writer.writerow(["Skills", ", ".join(student_profile.get("skills", []))])
    writer.writerow(["Education", student_profile.get("education", "N/A")])
    writer.writerow(["Preferred Domain", student_profile.get("domain", "N/A")])
    writer.writerow(["Preferred Location", student_profile.get("location", "N/A")])
    writer.writerow(["Internship Type", student_profile.get("internship_type", "N/A")])
    writer.writerow(["Readiness Score", f"{readiness_score}%"])
    writer.writerow([])

    # ── Section 2: Recommended Internships ────────────────────────────────
    writer.writerow(["=== RECOMMENDED INTERNSHIPS ==="])
    writer.writerow(["Rank", "Title", "Company", "Location", "Match Score", "Apply Link"])
    for rec in recommendations:
        writer.writerow([
            rec.get("rank", ""),
            rec.get("title", ""),
            rec.get("company", ""),
            rec.get("location", ""),
            f"{rec.get('match_score', 0)}%",
            rec.get("apply_link", ""),
        ])
    writer.writerow([])

    # ── Section 3: Skill Gap Analysis ─────────────────────────────────────
    writer.writerow(["=== SKILL GAP ANALYSIS ==="])
    writer.writerow(["Category", "Skills"])
    writer.writerow(["Your Skills", ", ".join(skill_gap.get("student_skills", set()))])
    writer.writerow(["Matching Skills", ", ".join(skill_gap.get("matching_skills", set()))])
    writer.writerow(["Missing Skills", ", ".join(skill_gap.get("missing_skills", set()))])
    writer.writerow(["Skill Match %", f"{skill_gap.get('match_percentage', 0)}%"])
    writer.writerow([])

    # ── Section 4: Report Metadata ────────────────────────────────────────
    writer.writerow(["=== REPORT METADATA ==="])
    writer.writerow(["Generated On", datetime.now().strftime("%B %d, %Y at %I:%M %p")])
    writer.writerow(["Generated By", "Internship Navigator AI"])

    return output.getvalue().encode("utf-8")


def generate_pdf_report(
    student_profile: dict,
    recommendations: list[dict],
    skill_gap: dict,
    readiness_score: float,
    domain_prediction: dict = None,
) -> bytes:
    """
    Generate a professional PDF report.

    Returns
    -------
    bytes
        PDF file content as bytes.
    """
    if not HAS_FPDF:
        # Fallback: return a simple text version that also shows the import error
        fallback_text = _generate_text_report(
            student_profile, recommendations, skill_gap,
            readiness_score, domain_prediction
        )
        if FPDF_ERROR:
            error_msg = f"\n\n--- FPDF IMPORT ERROR ---\n{FPDF_ERROR}\n".encode("utf-8")
            return fallback_text + error_msg
        return fallback_text

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # ── Title ─────────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(30, 64, 175)  # Blue
    pdf.cell(0, 15, "Internship Navigator AI", ln=True, align="C")
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 8, "Personalized Internship Readiness Report", ln=True, align="C")
    pdf.cell(
        0, 8,
        f"Generated on {datetime.now().strftime('%B %d, %Y at %I:%M %p')}",
        ln=True, align="C",
    )
    pdf.ln(10)

    # ── Section: Student Profile ──────────────────────────────────────────
    _pdf_section_header(pdf, "Student Profile")
    _pdf_key_value(pdf, "Name", student_profile.get("name", "N/A"))
    _pdf_key_value(pdf, "Education", student_profile.get("education", "N/A"))
    _pdf_key_value(pdf, "Skills", ", ".join(student_profile.get("skills", [])))
    _pdf_key_value(pdf, "Preferred Domain", student_profile.get("domain", "N/A"))
    _pdf_key_value(pdf, "Location", student_profile.get("location", "N/A"))
    _pdf_key_value(pdf, "Internship Type", student_profile.get("internship_type", "N/A"))
    pdf.ln(5)

    # ── Section: Readiness Score ──────────────────────────────────────────
    _pdf_section_header(pdf, "Internship Readiness Score")
    pdf.set_font("Helvetica", "B", 28)
    if readiness_score >= 70:
        pdf.set_text_color(22, 163, 74)  # Green
    elif readiness_score >= 40:
        pdf.set_text_color(234, 179, 8)   # Yellow
    else:
        pdf.set_text_color(220, 38, 38)   # Red
    pdf.cell(0, 15, f"{readiness_score}% Ready", ln=True, align="C")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(5)

    # ── Section: Domain Prediction ────────────────────────────────────────
    if domain_prediction:
        _pdf_section_header(pdf, "Predicted Career Domain")
        _pdf_key_value(
            pdf, "Domain",
            domain_prediction.get("predicted_domain", "N/A"),
        )
        _pdf_key_value(
            pdf, "Confidence",
            f"{domain_prediction.get('confidence', 0)}%",
        )
        pdf.ln(5)

    # ── Section: Top Recommendations ──────────────────────────────────────
    _pdf_section_header(pdf, "Top Internship Recommendations")
    for rec in recommendations[:10]:
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(30, 64, 175)
        title = f"#{rec.get('rank', '')} {rec.get('title', '')} - {rec.get('match_score', 0)}% Match"
        # Sanitize for latin-1
        title = title.encode("latin-1", errors="replace").decode("latin-1")
        pdf.cell(0, 7, title, ln=True)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(80, 80, 80)
        company = f"   {rec.get('company', '')} | {rec.get('location', '')}"
        company = company.encode("latin-1", errors="replace").decode("latin-1")
        pdf.cell(0, 5, company, ln=True)
        pdf.ln(2)
    pdf.ln(5)

    # ── Section: Skill Gap ────────────────────────────────────────────────
    _pdf_section_header(pdf, "Skill Gap Analysis")
    matching = skill_gap.get("matching_skills", set())
    missing = skill_gap.get("missing_skills", set())

    _pdf_key_value(pdf, "Skills You Have", ", ".join(sorted(matching)) if matching else "None identified")
    _pdf_key_value(pdf, "Skills to Learn", ", ".join(sorted(missing)) if missing else "None - Great job!")
    _pdf_key_value(pdf, "Skill Coverage", f"{skill_gap.get('match_percentage', 0)}%")

    # ── Footer ────────────────────────────────────────────────────────────
    pdf.ln(15)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 5, "This report was generated by Internship Navigator AI.", ln=True, align="C")
    pdf.cell(0, 5, "Recommendations are based on TF-IDF similarity matching and ML domain prediction.", ln=True, align="C")

    pdf_bytes = pdf.output(dest="S")
    return bytes(pdf_bytes)

def _pdf_section_header(pdf: FPDF, title: str):
    """Render a styled section header."""
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(30, 64, 175)
    pdf.cell(0, 10, title, ln=True)
    pdf.set_draw_color(30, 64, 175)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)
    pdf.set_text_color(0, 0, 0)


def _pdf_key_value(pdf, key, value):
    # Sanitize value to remove unicode characters unsupported by Helvetica
    value_safe = str(value).encode("latin-1", errors="replace").decode("latin-1")

    pdf.set_font("Arial", "B", 10)
    pdf.cell(40, 6, f"{key}:", ln=False)

    pdf.set_font("Arial", "", 10)

    # remaining width
    remaining_width = pdf.w - pdf.r_margin - pdf.get_x()

    if remaining_width < 20:
        pdf.ln(6)
        remaining_width = pdf.w - pdf.l_margin - pdf.r_margin

    pdf.multi_cell(remaining_width, 6, value_safe)



def _generate_text_report(
    student_profile, recommendations, skill_gap,
    readiness_score, domain_prediction,
) -> bytes:
    """Fallback text report when fpdf2 is unavailable."""

    lines = []
    lines.append("=" * 60)
    lines.append("    INTERNSHIP NAVIGATOR AI - READINESS REPORT")
    lines.append("=" * 60)
    lines.append("")
    lines.append(f"Generated: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}")
    lines.append("")

    # ---------------- PROFILE ----------------
    lines.append("--- STUDENT PROFILE ---")
    name = student_profile.get("name", "N/A")
    skills = student_profile.get("skills", [])

    # safe conversion
    skills_str = ", ".join(map(str, skills)) if isinstance(skills, (list, tuple, set)) else str(skills)

    lines.append(f"Name: {name}")
    lines.append(f"Skills: {skills_str}")
    lines.append(f"Readiness Score: {readiness_score}%")
    lines.append(f"Predicted Domain: {domain_prediction}")
    lines.append("")

    # ---------------- RECOMMENDATIONS ----------------
    lines.append("--- TOP RECOMMENDATIONS ---")

    for rec in (recommendations or [])[:10]:
        lines.append(
            f"  #{rec.get('rank', '-') } "
            f"{rec.get('title', 'Unknown')} at {rec.get('company', 'Unknown')} "
            f"- {rec.get('match_score', 0)}% match"
        )

    lines.append("")

    # ---------------- SKILL GAP ----------------
    lines.append("--- SKILL GAP ---")

    missing = skill_gap.get("missing_skills", [])
    missing = set(missing) if isinstance(missing, (list, tuple, set)) else set()

    lines.append(f"Missing Skills: {', '.join(sorted(map(str, missing))) if missing else 'None'}")
    lines.append(f"Coverage: {skill_gap.get('match_percentage', 0)}%")

    return "\n".join(lines).encode("utf-8")